name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.3/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Create certs
        run: |
          echo "${{ secrets.BUILDBUDDY_ORG_CERT }}" > buildbuddy-cert.pem
          echo "${{ secrets.BUILDBUDDY_ORG_KEY }}" > buildbuddy-key.pem
      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build --config=ci //...
